CREATE TABLE HN (
    hacker_name TEXT primary key,
    first_name TEXT,
    last_name TEXT,
    hacking_method TEXT,
    no_hacks INT,
    hack_rating INT
);
INSERT INTO HN (hacker_name, first_name, last_name, hacking_method, no_hacks, hack_rating) VALUES
  ('Phiber_Optik', 'Mark', 'Abene', 'Social Engineering', 12, 88),
  ('Kayla', 'Ryan', 'Ackroyd', 'SQL Injection', 9, 82),
  ('Tflow', 'Mustafa', 'Al-Bassam', 'DDoS', 14, 86),
  ('ioerror', 'Jacob', 'Appelbaum', 'Tor Exploits', 7, 80),
  ('Mendax', 'Julian', 'Assange', 'Data Leaks', 18, 90),
  ('weev', 'Andrew', 'Auernheimer', 'AT&T Exploit', 11, 84),
  ('The_Mentor', 'Loyd', 'Blankenship', 'BBS Intrusion', 6, 78),
  ('Erik_Bloodaxe', 'Chris', 'Goggans', 'Network Breach', 10, 83),
  ('Yuyo', 'Raúl', 'Barragán', 'Malware Deployment', 15, 87),
  ('RBCP', 'Brad', 'Carter', 'Phone Phreaking', 13, 81),
  ('crimew', 'maia', 'arson', 'Data Dumping', 16, 89),
  ('El_Chacal', 'Daniel', 'Sentinelli', 'Trojan Injection', 8, 79),
  ('Captain_Crunch', 'John', 'Draper', 'Phone Exploits', 20, 91),
  ('Dead_Lord', 'Bruce', 'Fancher', 'System Cracking', 9, 82),
  ('Kingpin', 'Joe', 'Grand', 'Hardware Hacking', 7, 77),
  ('Romanpoet', 'Virgil', 'Griffith', 'Blockchain Exploits', 10, 85),
  ('Guccifer', 'Marcel', 'Lazăr', 'Email Breach', 17, 88),
  ('Guccifer_2.0', 'Unknown', 'Unknown', 'Election Hacking', 19, 90),
  ('Kevin_Mitnick', 'Kevin', 'Mitnick', 'Social Engineering', 25, 95),
  ('Gary_McKinnon', 'Gary', 'McKinnon', 'Military Network Breach', 22, 92),
  ('Albert_Gonzalez', 'Albert', 'Gonzalez', 'Credit Card Theft', 30, 94),
  ('Adrian_Lamo', 'Adrian', 'Lamo', 'Unauthorized Access', 12, 83),
  ('Jeanson_James_Ancheta', 'Jeanson', 'Ancheta', 'Botnet Control', 14, 85),
  ('Jonathan_James', 'Jonathan', 'James', 'NASA Breach', 10, 80),
  ('Michael_Caldeira', 'Michael', 'Caldeira', 'Banking Exploits', 11, 82),
  ('Matthew_Bevan', 'Matthew', 'Bevan', 'Military Espionage', 13, 84),
  ('Richard_Pryce', 'Richard', 'Pryce', 'Government Hacking', 15, 86),
  ('Ehud_Tenenbaum', 'Ehud', 'Tenenbaum', 'Defense Systems Breach', 17, 88),
  ('Max_Butler', 'Max', 'Butler', 'Credit Card Fraud', 20, 90),
  ('Vladimir_Levin', 'Vladimir', 'Levin', 'Bank Transfer Hacks', 18, 89),
  ('Kristina_Svechinskaya', 'Kristina', 'Svechinskaya', 'Bank Trojan', 16, 87),
  ('Anonymous', 'Various', 'Hacktivists', 'DDoS', 100, 93),
  ('Lizard_Squad', 'Various', 'Members', 'Gaming Network Attacks', 40, 88),
  ('The_Jester', 'Unknown', 'Unknown', 'Counter-Hacking', 22, 91),
  ('Sabu', 'Hector', 'Monsegur', 'LulzSec Ops', 25, 92),
  ('Jeremy_Hammond', 'Jeremy', 'Hammond', 'Political Hacks', 19, 89),
  ('Chris_Putnam', 'Chris', 'Putnam', 'Facebook Exploit', 8, 78),
  ('Samy_Kamkar', 'Samy', 'Kamkar', 'MySpace Worm', 10, 80),
  ('George_Hotz', 'George', 'Hotz', 'iPhone Jailbreak', 12, 84),
  ('Malcolm_Hall', 'Malcolm', 'Hall', 'Corporate Espionage', 15, 86)
SELECT * FROM HN;
DELETE FROM HN WHERE hacker_rating < 80;